name: Extract Templates

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        starter: ['angular', 'javascript', 'react', 'svelte', 'typescript', 'vue']

    steps:
      - uses: actions/checkout@v3
      - run: |
          # create output directory
          mkdir dist/

          # copy template to output directory
          cp -r apps/nativescript-starter-${{ matrix.starter }} dist/

          # enter template directory
          cd dist/nativescript-starter-${{ matrix.starter }}

          # Remove nx project config
          rm project.json
          
          # Replace App_Resources path in the config
          sed -i 's/\.\.\/\.\.\/tools\/assets\/App_Resources/App_Resources/g' nativescript.config.ts

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ matrix.starter }}
          FOLDER: dist/nativescript-starter-${{ matrix.starter }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}